Repository lokalise/node-core, pull requests merged in 2023-12, with the labels that each got.

#85 Revise codeowners
  CODEOWNERS
Labels: skip-release

#86 Add isError typeguard
  package.json
  src/utils/typeUtils.spec.ts
  src/utils/typeUtils.ts
Labels: minor

#87 Switch to undici 6
  README.md
  package.json
Labels: minor

#89 Fix compatibility with new Pino version
  package.json
  src/errors/globalErrorHandler.spec.ts
  src/errors/globalErrorHandler.ts
Labels: patch

#88 HTTP Client lib: make request label option mandatory
  README.md
  package.json
  src/http/httpClient.ts
Labels: skip-release

#90 Make error handling more consistent
  package.json
  src/http/httpClient.spec.ts
  src/http/httpClient.ts
Labels: major

#82 Add failure/success helpers to either.ts
  README.md
  src/errors/either.ts
Labels: minor

#91 Export either helpers
  index.ts
Labels: minor

#92 Multirepo-friendly logging configuration
  .eslintignore
  README.md
  index.ts
  src/logging/example.script.js
  src/logging/loggerConfigResolver.ts
Labels: minor

#93 Support passing base for logs
  src/logging/__snapshots__/loggerConfigResolver.spec.ts.snap
  src/logging/loggerConfigResolver.ts
  src/utils/__snapshots__/objectUtils.spec.ts.snap
Labels: minor
