Repository lokalise/node-core, pull requests merged in 2023-11, with the labels that each got.

#76 Array to record
  docs/array-utils.md
  docs/object-utils.md
  index.ts
  src/utils/__snapshots__/objectUtils.spec.ts.snap
  src/utils/arrayUtils.spec.ts
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: major

#77 Convert date to string
  docs/object-utils.md
  index.ts
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: minor

#78 Group by bug fix
  docs/object-utils.md
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: bug, patch

#79 Fix PublicNonRecoverableError typeguard
  src/utils/typeUtils.ts
Labels: patch

#80 Convert date fields to iso string array handling
  package.json
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: bug, patch

#83 AP-1334 Added deepClone method
  docs/object-utils.md
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: minor

#84 Added deepClone into export
  index.ts
Labels: patch
