Repository lokalise/node-core, pull requests merged in 2023-08, with the labels that each got.

#64 Add getOptionalValidatedInteger method
  README.md
  src/config/ConfigScope.spec.ts
  src/config/ConfigScope.ts
Labels: patch

#65 Empty string should count as null
  src/config/ConfigScope.spec.ts
  src/config/ConfigScope.ts
Labels: major

#67 Implement waitAndRetry
  README.md
  index.ts
  src/utils/waitUtils.spec.ts
  src/utils/waitUtils.ts
Labels: minor
