Repository lokalise/node-core, pull requests merged in 2023-10, with the labels that each got.

#72 Fix export for sendPostBinary
  index.ts
Labels: patch

#73 Array remove nullish
  docs/array-utils.md
  index.ts
  src/utils/arrayUtils.spec.ts
  src/utils/arrayUtils.ts
Labels: minor

#74 Implement support for request labels
  .eslintrc.json
  README.md
  package.json
  src/errors/ResponseStatusError.ts
  src/http/httpClient.spec.ts
  src/http/httpClient.ts
Labels: major
