Repository lokalise/node-core, pull requests merged in 2023-04, with the labels that each got.

#43 Breaking change: Updated ConfigScope.getOptional to fallback to default value when environment variable is an empty string ('')
  src/config/ConfigScope.spec.ts
  src/config/ConfigScope.ts
Labels: bug, major

#44 Update dependencies
  package.json
Labels: patch

#45 Implement response schema validation
  index.ts
  package.json
  src/http/httpClient.spec.ts
  src/http/httpClient.ts
Labels: minor

#47 Introduce ResponseStatusError
  index.ts
  src/errors/ResponseStatusError.ts
  src/http/httpClient.ts
Labels: minor

#48 Add generic to ResponseStatusError
  src/errors/InternalError.ts
  src/errors/ResponseStatusError.ts
Labels: minor

#49 Add type-safe access to response
  src/errors/ResponseStatusError.ts
  src/http/httpClient.spec.ts
Labels: minor

#50 Fix error name and types
  src/errors/ResponseStatusError.ts
Labels: minor
