Repository lokalise/node-core, pull requests merged in 2024-09, with the labels that each got.

#153 adjust checking for internal and public errors
  index.ts
  package.json
  src/errors/InternalError.spec.ts
  src/errors/InternalError.ts
  src/errors/PublicNonRecoverableError.spec.ts
  src/errors/PublicNonRecoverableError.ts
  src/errors/errorTypeGuards.ts
  src/utils/typeUtils.spec.ts
  src/utils/typeUtils.ts
Labels: patch

#158 AP-5078 MultiTransactionObservabilityManager
  package.json
  src/observability/MultiTransactionObservabilityManager.spec.ts
  src/observability/MultiTransactionObservabilityManager.ts
Labels: minor

#159 Fixing lint issues on release action
  package.json
Labels: skip-release

#160 Exporting MultiTransactionObservabilityManager
  index.ts
Labels: patch

#161 Unpin a specific version of @vitest/coverage-v8 and vitest
  package.json
Labels: patch

#162 Add logger resolvers
  index.ts
  package.json
  src/logging/loggerConfigResolver.spec.ts
  src/logging/loggerConfigResolver.ts
Labels: minor

#163 Fix config type for monorepo loggers
  src/logging/loggerConfigResolver.ts
Labels: patch
