Repository lokalise/node-core, pull requests merged in 2024-04, with the labels that each got.

#115 DXP-277 Add tslib dependency
  package.json
Labels: minor

#116 Apply timeout correctly by default
  .eslintignore
  CHANGELOG.md
  src/http/httpClient.ts
  vitest.config.mts
Labels: minor

#117 Reduce default timeout
  CHANGELOG.md
  README.md
  src/http/httpClient.ts
Labels: patch

#118 Add passthrough of error.cause for PublicNonRecoverableError & InternalError
  src/errors/InternalError.ts
  src/errors/PublicNonRecoverableError.ts
  src/errors/publicErrors.ts
Labels: minor

#120 Exposing isError
  CHANGELOG.md
  index.ts
Labels: patch

#121 Add missing requestLabel
  CHANGELOG.md
  src/http/httpClient.ts
Labels: patch

#122 Implement copy without empty
  CHANGELOG.md
  index.ts
  src/utils/objectUtils.spec.ts
  src/utils/objectUtils.ts
Labels: minor

#124 Run tests with Node 22
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: skip-release

#126 Add isLevelEnabled to common logger interface
  src/logging/commonLogger.ts
Labels: minor
